### PR TITLE
Order dependency update

### PR DESCRIPTION
**Pull request by xzzz3**
Adding the dependency relations in Order.

Currently the dependencies are all working as tested (tested the happy path, not odd user inputs). For the happy path, the following conditions are required: at least 1 free driver, at least 1 customer and must create the order with the phone number of that customer, at least 1 dish and must create the order with the dishes in the menu.

However I am facing an issue where nothing gets saved to the storage after the app is closed and there doesn't seem to be any error messages. Will check again tmr to hopefully locate the bug.

### CODE REVIEW

**Comment by xzzz3** [comment]
Storage issue has been fixed, the app is working as expected.

Note: If the app doesn't work when you try to launch it, try removing the Json storage file in your data folder, since that may cause reading errors as I changed parts of how an order is read by the storage. After that, it should work fine

**Review by hieunm1821 — APPROVED** [review]
LGTM! Nice work.

**Review by zxgoh — APPROVED** [review]
Looks nice!

**Comment by xzzz3** [comment]
Merging the PR!

**Pull request merged**
