### PR TITLE
Add revenue feature

### PR DESCRIPTION
**Pull request by jaegarpoon**
Usage: `revenue` 

Provides view of delivered orders and sums up the total revenue for the day in the response box

**Unable to test yet since @xzzz3 PR has not been merged, so no way to update the order status. Best to merge after #106 is merged

### CODE REVIEW

**Comment by jaegarpoon** [comment]
List view for revenue command to show ALL orders instead of just orders which are delivered and within current day.
-> if filtered to show within current day only, mark/delete order command will be affected

**Comment by jaegarpoon** [comment]
> let us know when it is ready for review after testing with the new Order PR!

tested! works fine :)

**Comment by jaegarpoon** [comment]
@xzzz3 @zxgoh @hieunm1821 just tested revenue feature under multiple conditions, works fine on my end and should be ready to review!

**Review by hieunm1821 — APPROVED** [review]
LGTM!

**Review by xzzz3 — APPROVED** [review]
nice!

**Pull request merged**
