### PR TITLE
Add list order functionality

### PR DESCRIPTION
**Pull request by jaegarpoon**
Usage: `listorder KEYWORD`, where `KEYWORD` is one of `ALL, IN_PROGRESS, DELIVERED, CANCELLED` (not case-sensitive)

Additional checks: 
* Only allows 1 argument to be passed after listorder
* Checks if argument passed is either `ALL` or one of the OrderStatus

### CODE REVIEW

**Comment by jaegarpoon** [comment]
Fixes #2, #4

**Comment by jaegarpoon** [comment]
@hieunm1821 if possible could you give some inputs on the additional checks done? Mostly adapted from listdriver command, if its ok perhaps you can add it into listdriver too!

**Review by xzzz3 — APPROVED** [review]
looks good!

**Review by hieunm1821 — APPROVED** [review]
LGTM!

**Pull request merged**
